-- Add additional profile fields to users table
ALTER TABLE USERS
    ADD COLUMN BIO TEXT NULL;

ALTER TABLE USERS
    ADD COLUMN LOCATION VARCHAR(
        255
    ) NULL;

ALTER TABLE USERS
    ADD COLUMN PHONE VARCHAR(
        20
    ) NULL;

ALTER TABLE USERS
    ADD COLUMN DATE_OF_BIRTH DATE NULL;

ALTER TABLE USERS
    ADD COLUMN LINKEDIN_URL VARCHAR(
        255
    ) NULL;

ALTER TABLE USERS
    ADD COLUMN TWITTER_URL VARCHAR(
        255
    ) NULL;

ALTER TABLE USERS
    ADD COLUMN WEBSITE_URL VARCHAR(
        255
    ) NULL;

-- Add indexes for searchable fields
CREATE INDEX IDX_USERS_LOCATION ON USERS(LOCATION);

CREATE INDEX IDX_USERS_DATE_OF_BIRTH ON USERS(DATE_OF_BIRTH);