CREATE TABLE IF NOT EXISTS GAMES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SERIES_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    DATE DATE NOT NULL,
    TIME TIME NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    MAX_PLAYERS INT NOT NULL,
    STATUS ENUM('scheduled', 'in_progress', 'completed', 'cancelled') NOT NULL DEFAULT 'scheduled',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SERIES_ID) REFERENCES GAME_SERIES(ID) ON DELETE CASCADE
);