-- Create TEAM_INVITATIONS table for team invitation system
CREATE TABLE IF NOT EXISTS TEAM_INVITATIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TEAM_ID INT NOT NULL,
    INVITED_BY_USER_ID INT NOT NULL,
    INVITED_EMAIL VARCHAR(100) NOT NULL,
    INVITED_ROLE ENUM('captain', 'player') NOT NULL DEFAULT 'player',
    INVITATION_TOKEN VARCHAR(255) NOT NULL UNIQUE,
    STATUS ENUM('pending', 'accepted', 'declined', 'expired') NOT NULL DEFAULT 'pending',
    EXPIRES_AT TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (INVITED_BY_USER_ID) REFERENCES USERS(ID),
    INDEX IDX_TEAM_INVITATIONS_EMAIL (INVITED_EMAIL),
    INDEX IDX_TEAM_INVITATIONS_TOKEN (INVITATION_TOKEN),
    INDEX IDX_TEAM_INVITATIONS_STATUS (STATUS),
    INDEX IDX_TEAM_INVITATIONS_EXPIRES (EXPIRES_AT)
);